"""
CrystalDiskInfo Integration Module for HELXAID.

Component Name: CrystalDiskInfoIntegration
Provides high-fidelity disk health, temperature, and S.M.A.R.T. telemetry
extracted from CrystalDiskInfo CLI (/CopyExit) across internal NVMe, SATA,
and external USB/Thunderbolt enclosures.
"""

from __future__ import annotations

import os
import re
import sys
import time
import shutil
import tempfile
import subprocess
from typing import Dict, List, Optional, Tuple


_CDI_CACHE: Dict[str, Dict] = {}
_CDI_LAST_SCAN_TIME: float = 0.0
_CDI_CACHE_TTL: float = 30.0  # Cache duration in seconds to prevent excessive process spawns


def get_crystal_disk_info_path() -> Optional[str]:
    """
    Locate DiskInfo64.exe or DiskInfo32.exe strictly inside HELXAID tools directory.
    Priority:
    1. Project root / portable tools: HELXAID/tools/crystaldiskinfo/DiskInfo64.exe
    2. AppData tools: %APPDATA%/HELXAID/tools/crystaldiskinfo/DiskInfo64.exe
    3. PyInstaller bundle dir: sys._MEIPASS/tools/crystaldiskinfo/DiskInfo64.exe
    """
    candidates = []

    # 1. Base directory (project root or next to executable)
    base_dir = getattr(sys, '_MEIPASS', os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    exe_dir = os.path.dirname(sys.executable)
    
    candidates.extend([
        os.path.join(base_dir, "tools", "crystaldiskinfo", "DiskInfo64.exe"),
        os.path.join(base_dir, "tools", "crystaldiskinfo", "DiskInfo32.exe"),
        os.path.join(exe_dir, "tools", "crystaldiskinfo", "DiskInfo64.exe"),
        os.path.join(exe_dir, "tools", "crystaldiskinfo", "DiskInfo32.exe"),
        os.path.join(os.path.dirname(base_dir), "tools", "crystaldiskinfo", "DiskInfo64.exe"),
        os.path.join(os.path.dirname(base_dir), "tools", "crystaldiskinfo", "DiskInfo32.exe"),
    ])

    # 2. AppData Roaming tools
    appdata = os.environ.get("APPDATA", "")
    if appdata:
        candidates.extend([
            os.path.join(appdata, "HELXAID", "tools", "crystaldiskinfo", "DiskInfo64.exe"),
            os.path.join(appdata, "HELXAID", "tools", "crystaldiskinfo", "DiskInfo32.exe"),
        ])

    for path in candidates:
        if path and os.path.exists(path):
            return os.path.abspath(path)

    return None


def is_crystal_disk_info_available() -> bool:
    """Check if CrystalDiskInfo executable is present."""
    return get_crystal_disk_info_path() is not None


def parse_crystal_disk_info_text(content: str) -> Dict[str, Dict]:
    """
    Parse the raw text content of DiskInfo.txt generated by CrystalDiskInfo /CopyExit.
    Returns a dictionary keyed by disk index (e.g., '0', '1'):
    {
        '0': {
            'index': 0,
            'model': 'WD_BLACK SN7100 1TB',
            'health_pct': 98,
            'status': 'HEALTHY',
            'health_text': '98% HEALTHY',
            'temp': 39,
            'media_type': 'NVMe SSD',
            'power_on_hours': 450,
            'power_on_count': 320,
            'drive_letters': ['C:', 'D:'],
            'raw_health_status': 'Good (98 %)',
            'source': 'crystaldiskinfo',
        }
    }
    """
    if not content or not content.strip():
        return {}

    disks: Dict[str, Dict] = {}

    # Split into sections by disk delimiter header
    # e.g., "----------------------------------------------------------------------------\n (01) WD_BLACK SN7100 1TB\n----------------------------------------------------------------------------"
    disk_blocks = re.split(r'-{40,}\s*\n\s*\(([0-9]+)\)\s*([^\n]+)\s*\n\s*-{40,}', content)

    # First block is preamble / summary
    # Subsequent items come in triplets: [preamble, disk_num, header_model, block_body, disk_num, header_model, block_body, ...]
    if len(disk_blocks) >= 4:
        for i in range(1, len(disk_blocks), 3):
            if i + 2 >= len(disk_blocks):
                break
            raw_idx = disk_blocks[i].strip()
            header_model = disk_blocks[i+1].strip()
            body = disk_blocks[i+2]

            try:
                # CrystalDiskInfo is 1-indexed (01, 02), Windows physical drive is 0-indexed (0, 1)
                disk_idx = int(raw_idx) - 1
            except ValueError:
                disk_idx = len(disks)

            disk_key = str(disk_idx)

            # Extract fields with regex
            model_m = re.search(r'^\s*Model\s*:\s*(.+)$', body, re.MULTILINE | re.IGNORECASE)
            model = model_m.group(1).strip() if model_m else header_model

            # Health Status
            health_m = re.search(r'^\s*Health Status\s*:\s*([^\n]+)$', body, re.MULTILINE | re.IGNORECASE)
            health_raw = health_m.group(1).strip() if health_m else "Good (100 %)"
            
            # Extract percentage from "Good (98 %)" or "Good (100 %)" or "Caution (85 %)"
            pct_m = re.search(r'(\d+)\s*%', health_raw)
            if pct_m:
                health_pct = int(pct_m.group(1))
            elif "GOOD" in health_raw.upper():
                health_pct = 100
            elif "CAUTION" in health_raw.upper() or "WARNING" in health_raw.upper():
                health_pct = 50
            elif "BAD" in health_raw.upper() or "CRITICAL" in health_raw.upper():
                health_pct = 10
            else:
                health_pct = 100

            # Normalized status
            if health_pct >= 90:
                status = "HEALTHY"
            elif health_pct >= 60:
                status = "WARNING"
            else:
                status = "CRITICAL"

            # Temperature
            temp_m = re.search(r'^\s*Temperature\s*:\s*(\d+)\s*C', body, re.MULTILINE | re.IGNORECASE)
            temp_c = int(temp_m.group(1)) if temp_m else 0

            # Rotation Rate / Media Type
            rot_m = re.search(r'^\s*Rotation Rate\s*:\s*([^\n]+)$', body, re.MULTILINE | re.IGNORECASE)
            iface_m = re.search(r'^\s*Interface\s*:\s*([^\n]+)$', body, re.MULTILINE | re.IGNORECASE)
            rot_str = rot_m.group(1).strip().upper() if rot_m else ""
            iface_str = iface_m.group(1).strip().upper() if iface_m else ""

            if "NVME" in iface_str or "NVM EXPRESS" in iface_str or "NVME" in model.upper():
                media_type = "NVMe SSD"
            elif "SSD" in rot_str or "SSD" in iface_str or "SOLID STATE" in rot_str or "SSD" in model.upper():
                media_type = "SSD"
            elif "RPM" in rot_str or "HDD" in model.upper():
                media_type = "HDD"
            else:
                media_type = "SSD" if any(kw in (model + " " + iface_str).upper() for kw in ("SSD", "NVME", "M.2", "UASP", "KYO")) else "Storage"

            # Power On Hours & Count
            poh_m = re.search(r'^\s*Power On Hours\s*:\s*(\d+)', body, re.MULTILINE | re.IGNORECASE)
            poh = int(poh_m.group(1)) if poh_m else 0

            poc_m = re.search(r'^\s*Power On Count\s*:\s*(\d+)', body, re.MULTILINE | re.IGNORECASE)
            poc = int(poc_m.group(1)) if poc_m else 0

            # Drive Letters
            let_m = re.search(r'^\s*Drive Letter\s*:\s*([^\n]+)$', body, re.MULTILINE | re.IGNORECASE)
            drive_letters = re.findall(r'([A-Z]:)', let_m.group(1).upper()) if let_m else []

            wear = max(0, min(100, 100 - health_pct))

            disks[disk_key] = {
                "index": disk_idx,
                "model": model,
                "health_pct": health_pct,
                "wear": wear,
                "status": status,
                "health_text": f"{health_pct}% {status}",
                "temp": temp_c,
                "media_type": media_type,
                "power_on_hours": poh,
                "power_on_count": poc,
                "drive_letters": drive_letters,
                "raw_health_status": health_raw,
                "source": "crystaldiskinfo",
            }

    return disks


def is_process_elevated() -> bool:
    """Check if current process has Administrator privileges."""
    try:
        import ctypes
        return ctypes.windll.shell32.IsUserAnAdmin() != 0
    except Exception:
        return False


def query_crystal_disk_info(force_refresh: bool = False, timeout: int = 8) -> Dict[str, Dict]:
    """
    Execute CrystalDiskInfo /CopyExit and parse DiskInfo.txt with TTL caching.
    
    Can be called directly from elevated process (service) or elevated client.
    Non-elevated client callers are automatically routed via HelxaidHelperService IPC.
    Returns: Dict[str, Dict] mapping drive index ('0', '1', ...) to telemetry dict.
    """
    global _CDI_CACHE, _CDI_LAST_SCAN_TIME

    now = time.time()
    if not force_refresh and _CDI_CACHE and (now - _CDI_LAST_SCAN_TIME < _CDI_CACHE_TTL):
        return _CDI_CACHE

    cdi_exe = get_crystal_disk_info_path()
    if not cdi_exe or not os.path.exists(cdi_exe):
        return _CDI_CACHE

    # If not running as administrator, direct subprocess.run of DiskInfo64.exe will fail with WinError 740.
    # Route through elevated HelxaidHelperService instead.
    if not is_process_elevated():
        try:
            from integrations.cpu_controller import send_service_command
            svc = send_service_command({"action": "get_drive_health"})
            if svc and svc.get("status") == "success":
                counters = svc.get("counters", {})
                converted = {}
                for dev_id, c in counters.items():
                    wear = int(c.get("Wear", 0) or 0)
                    health_pct = int(c.get("HealthPct", 100 - wear))
                    converted[str(dev_id)] = {
                        "index": int(dev_id) if str(dev_id).isdigit() else 0,
                        "model": str(c.get("Model", "")),
                        "health_pct": health_pct,
                        "wear": wear,
                        "status": str(c.get("Status", "HEALTHY")),
                        "health_text": f"{health_pct}% {c.get('Status', 'HEALTHY')}",
                        "temp": int(c.get("Temperature", 0) or 0),
                        "media_type": str(c.get("MediaType", "SSD")),
                        "source": str(c.get("Source", "service")),
                    }
                if converted:
                    _CDI_CACHE = converted
                    _CDI_LAST_SCAN_TIME = time.time()
                    return converted
        except Exception:
            pass
        return _CDI_CACHE

    temp_dir = tempfile.mkdtemp(prefix="helxaid_cdi_")
    try:
        # Create minimal DiskInfo.ini in temp directory for silent non-interactive execution
        ini_path = os.path.join(temp_dir, "DiskInfo.ini")
        with open(ini_path, "w", encoding="utf-8") as f:
            f.write("[Setting]\nAutoRefresh=0\nStartup=0\nResident=0\nHideSerialNumber=0\n")

        # Execute DiskInfo64.exe /CopyExit
        creation_flags = 0x08000000  # CREATE_NO_WINDOW
        res = subprocess.run(
            [cdi_exe, "/CopyExit"],
            cwd=temp_dir,
            capture_output=True,
            timeout=timeout,
            creationflags=creation_flags
        )

        txt_path = os.path.join(temp_dir, "DiskInfo.txt")
        # Check temp dir first, then executable dir as fallback
        if not os.path.exists(txt_path):
            cdi_base = os.path.dirname(cdi_exe)
            alt_txt = os.path.join(cdi_base, "DiskInfo.txt")
            if os.path.exists(alt_txt):
                txt_path = alt_txt

        if os.path.exists(txt_path):
            with open(txt_path, "r", encoding="utf-8", errors="ignore") as f:
                raw_text = f.read()
            parsed = parse_crystal_disk_info_text(raw_text)
            if parsed:
                _CDI_CACHE = parsed
                _CDI_LAST_SCAN_TIME = time.time()
                return parsed
    except Exception as ex:
        if getattr(ex, 'winerror', None) != 740:
            print(f"[CrystalDiskInfo] Execution notice: {ex}")
    finally:
        try:
            shutil.rmtree(temp_dir, ignore_errors=True)
        except Exception:
            pass

    return _CDI_CACHE
